AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
