# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Activity.create(name: 'First Activity', email: 'first@activity.tv', phone: '111-11-11', description: 'description about awesomeness of the First Activity', map: 'coords')
Activity.create(name: 'Second Activity', email: 'second@activity.tv', phone: '111-11-22', description: 'description about awesomeness of the Second Activity', map: 'coords')
Activity.create(name: 'Third Activity', email: 'third@activity.tv', phone: '111-11-33', description: 'description about awesomeness of the Third  Activity', map: 'coords')
Activity.create(name: 'Fourth Activity', email: 'fourth@activity.tv', phone: '111-11-44', description: 'description about awesomeness of the Fourth Activity', map: 'coords')
Activity.create(name: 'Fifth Activity', email: 'fifth@activity.tv', phone: '111-11-55', description: 'description about awesomeness of the Fifth Activity', map: 'coords')
Activity.create(name: 'Sixth Activity', email: 'sixth@activity.tv', phone: '111-11-66', description: 'description about awesomeness of the Sixth Activity', map: 'coords')
Activity.create(name: 'Seventh Activity', email: 'seventh@activity.tv', phone: '111-11-77', description: 'description about awesomeness of the Seventh Activity', map: 'coords')
Activity.create(name: 'Eighth Activity', email: 'eighth@activity.tv', phone: '111-11-88', description: 'description about awesomeness of the Eighth Activity', map: 'coords')
Activity.create(name: 'Activity #9', email: 'ninth@activity.tv', phone: '111-11-99', description: 'description about awesomeness of the Ninth Activity', map: 'coords')
Activity.create(name: 'Activity #10', email: '10th@activity.tv', phone: '111-11-10', description: 'description about awesomeness of the 10th Activity', map: 'coords')
Activity.create(name: 'Activity #11', email: '11th@activity.tv', phone: '111-11-11', description: 'description about awesomeness of the 11th Activity', map: 'coords')
Activity.create(name: 'Activity #12', email: '12th@activity.tv', phone: '111-11-12', description: 'description about awesomeness of the 12th Activity', map: 'coords')
Activity.create(name: 'Activity #13', email: '13th@activity.tv', phone: '111-11-13', description: 'description about awesomeness of the 13th Activity', map: 'coords')
Activity.create(name: 'Activity #14', email: '14th@activity.tv', phone: '111-11-14', description: 'description about awesomeness of the 14th Activity', map: 'coords')
Activity.create(name: 'Activity #15', email: '15th@activity.tv', phone: '111-11-15', description: 'description about awesomeness of the 15th Activity', map: 'coords')
Activity.create(name: 'Activity #16', email: '16th@activity.tv', phone: '111-11-16', description: 'description about awesomeness of the 16th Activity', map: 'coords')
Activity.create(name: 'Activity #17', email: '17th@activity.tv', phone: '111-11-17', description: 'description about awesomeness of the 17th Activity', map: 'coords')
Activity.create(name: 'Activity #18', email: '18th@activity.tv', phone: '111-11-18', description: 'description about awesomeness of the 18th Activity', map: 'coords')
Activity.create(name: 'Activity #19', email: '19th@activity.tv', phone: '111-11-19', description: 'description about awesomeness of the 19th Activity', map: 'coords')
Activity.create(name: 'Activity #20', email: '20th@activity.tv', phone: '111-11-20', description: 'description about awesomeness of the 20th Activity', map: 'coords')
Activity.create(name: 'Activity #21', email: '21th@activity.tv', phone: '111-11-21', description: 'description about awesomeness of the 21th Activity', map: 'coords')
Activity.create(name: 'Activity #22', email: '22th@activity.tv', phone: '111-11-22', description: 'description about awesomeness of the 22th Activity', map: 'coords')
Activity.create(name: 'Activity #23', email: '23th@activity.tv', phone: '111-11-23', description: 'description about awesomeness of the 23th Activity', map: 'coords')
Activity.create(name: 'Activity #24', email: '24th@activity.tv', phone: '111-11-24', description: 'description about awesomeness of the 24th Activity', map: 'coords')
Activity.create(name: 'Activity #25', email: '25th@activity.tv', phone: '111-11-25', description: 'description about awesomeness of the 25th Activity', map: 'coords')
Activity.create(name: 'Activity #26', email: '26th@activity.tv', phone: '111-11-26', description: 'description about awesomeness of the 26th Activity', map: 'coords')
Activity.create(name: 'Activity #27', email: '27th@activity.tv', phone: '111-11-27', description: 'description about awesomeness of the 27th Activity', map: 'coords')
Activity.create(name: 'Activity #28', email: '28th@activity.tv', phone: '111-11-28', description: 'description about awesomeness of the 28th Activity', map: 'coords')
Activity.create(name: 'Activity #29', email: '29th@activity.tv', phone: '111-11-29', description: 'description about awesomeness of the 29th Activity', map: 'coords')
Activity.create(name: 'Activity #30', email: '30th@activity.tv', phone: '111-11-30', description: 'description about awesomeness of the 30th Activity', map: 'coords')
Activity.create(name: 'Activity #31', email: '31th@activity.tv', phone: '111-11-31', description: 'description about awesomeness of the 31th Activity', map: 'coords')
Activity.create(name: 'Activity #32', email: '32th@activity.tv', phone: '111-11-32', description: 'description about awesomeness of the 32th Activity', map: 'coords')
Activity.create(name: 'Activity #33', email: '33th@activity.tv', phone: '111-11-33', description: 'description about awesomeness of the 33th Activity', map: 'coords')
Activity.create(name: 'Activity #34', email: '34th@activity.tv', phone: '111-11-34', description: 'description about awesomeness of the 34th Activity', map: 'coords')
Activity.create(name: 'Activity #35', email: '35th@activity.tv', phone: '111-11-35', description: 'description about awesomeness of the 35th Activity', map: 'coords')
Activity.create(name: 'Activity #36', email: '36th@activity.tv', phone: '111-11-36', description: 'description about awesomeness of the 36th Activity', map: 'coords')
Activity.create(name: 'Activity #37', email: '37th@activity.tv', phone: '111-11-37', description: 'description about awesomeness of the 37th Activity', map: 'coords')
Activity.create(name: 'Activity #38', email: '38th@activity.tv', phone: '111-11-38', description: 'description about awesomeness of the 38th Activity', map: 'coords')
Activity.create(name: 'Activity #39', email: '39th@activity.tv', phone: '111-11-39', description: 'description about awesomeness of the 39th Activity', map: 'coords')
Activity.create(name: 'Activity #40', email: '40th@activity.tv', phone: '111-11-40', description: 'description about awesomeness of the 40th Activity', map: 'coords')
Activity.create(name: 'Activity #41', email: '41th@activity.tv', phone: '111-11-41', description: 'description about awesomeness of the 41th Activity', map: 'coords')

